### ISSUE TITLE
Request Body is always empty

### ISSUE THREAD

**Issue by esmyser** [alexfernandez/loadtest#101]
When using the API to generate a loadtest, the request body always comes through as an empty {}.

Here are my options:

```
var options = { 
 url : 'localhost:3000/admin/reserve',
 maxRequests : 1,
 contentType : 'application/json', 
 method : 'POST',
 body : { 'hi' : 'there' },
 debug : true 
};
```
If I log options.body before sending it to loadtest.loadTest, it logs it correctly. 

The debug prints out:
```
DEBUG Received JSON body
DEBUG Options: {"protocol":"http:","slashes":true,"auth":null,"host":"localhost:3000","port":"3000","hostname":"localhost","hash":null,"search":null,"query":null,"pathname":"/admin/reserve","path":"/admin/reserve","href":"http://localhost:3000/admin/reserve","headers":{"Content-Type":"application/json","user-agent":"node.js loadtest bot"},"agent":false,"method":"POST"}
```
So it looks like it's recognizing that there's a body, but then it's not including it in the options.

The body is also present at request.write(message) on line 217.

When I try to access request.body.hi in my app, it's undefined, and the request.body is just {}.

**Comment by esmyser** [comment]
I just needed to use content-type : application/x-www-form-urlencoded instead of application/json. closing.

**Comment by alexfernandez** [comment]
Thanks. So the body was being sent?

**Comment by esmyser** [comment]
The body wasn't being sent with application/json

Now that I'm using x-www-form-urlencoded it's being sent as:
  body: { "{ 'hi' : 'there' }": " " }

So not completely working yet. I am, admittedly, very new to coding.

**Comment by abenhamdine** [comment]
Same problem...

**Comment by ashokdey** [comment]
@esmyser , pass -T 'application/json' instead of ' x-www-form-urlencoded'
