### ISSUE TITLE
statusCallback `error` is not returning requestElapsed, requestIndex, instanceIndex

### ISSUE THREAD

**Issue by mkhan004** [alexfernandez/loadtest#107]
statusCallback(latency, result, error) `error` is not returning requestElapsed, requestIndex, instanceIndex. It is only returning `Status code 503` for a failed request with status code 503.

Here is some sample output for failed request:
latency:

```
{
  "totalRequests": 2000,
  "totalErrors": 2000,
  "totalTimeSeconds": 18.273976021,
  "rps": 109,
  "meanLatencyMs": 7270,
  "maxLatencyMs": 11178,
  "minLatencyMs": 5124,
  "percentiles": {
    "50": 6882,
    "90": 9284,
    "95": 10731,
    "99": 11055
  },
  "errorCodes": {
    "503": 516,
    "504": 1484
  }
}
```

result: 

```
504
```

error:

```
Status code 504
```

summary:

```
"data": {
      "totalRequests": 2000,
      "totalErrors": 2000,
      "totalTimeSeconds": 18.261542286,
      "rps": 110,
      "meanLatencyMs": 7270,
      "maxLatencyMs": 11178,
      "minLatencyMs": 5124,
      "percentiles": {
        "50": 6882,
        "90": 9284,
        "95": 10731,
        "99": 11055
      },
      "errorCodes": {
        "503": 516,
        "504": 1484
      },
      "instanceIndex": 0
}
```

Is there any way to get requestElapsed, requestIndex, instanceIndex and also headers for a failed request?

**Comment by alexfernandez** [comment]
Sadly, loadtest only tracks those values for correct requests. Can you please explain what is your use case to need them in errors also? Just curious, in my experience I have not ever needed that.

**Comment by mkhan004** [comment]
We had build a Performance Testing and Reporting tool using JMeter, Logstash, Elasticsearch and Kibana. JMeter was serving our initial needs but our team has decided not to use any UI based tool for performance/load testing. So we are going to build a complete performance/load testing and reporting app using most probably your `loadtest` and `ELK` stack.

From my research I found `loadtest` is a great tool to serve our almost all needs. 

But from my initial study I found that we can not capture actual `response`, `response Headers` and `requestIndex` for `failed` request. 

Use Case For Failed Request:
- Root cause analysis: For any failed request we do a root cause analysis to identify actual fact behind the issue. In that case just `status code` is not good enough, we need actual `response` which contains some custom error message or error stack which will help to drill down the actual cause.
- `response Headers` is another important piece of information which helps us to identify caching server status, server response content-type, request time. Here is an example of headers for passed request. Unfortunately currently I don't have sample Headers for Failed request, which could be very helpful to understand the need.
```
"headers": {
    "cache-control": "public, max-age=600",
    "content-type": "application/json",
    "date": "Fri, 19 Aug 2016 16:53:37 GMT",
    "server": "nginx/1.8.1",
    "content-length": "20307",
    "connection": "Close"
  }
```
- We need `instanceIndex ` for kibana reporting when we calculate number of simulated users using unique count of `instanceIndex `. If we can not capture `instanceIndex ` for failed request then our report will be misleading for number of simulated users.

These are some important logs developer always ask to research for any failed request.

**Comment by alexfernandez** [comment]
Thanks for your detailed response. Fair enough, I see it now. Care to send a pull request? Otherwise it might take me a while to get to it.

**Comment by mkhan004** [comment]
Sure I will send a pull request. Thanks.

**Comment by alexfernandez** [comment]
I have added your [three parameters](https://github.com/alexfernandez/loadtest/commit/487723064e22aaff66b8df3299110507c2dd4dd1). I think you can now get all the info you need from the second parameter if there is an error:

    options.statusCallback = function(error, result) {
        var host = result.host;
        var body = result.body;
        if (error) {
            console.error('Invalid result from host %s', host);
        }
    };

It is in the new version 2.0.0, let me know if this works for you so we can close this issue.

**Comment by mkhan004** [comment]
@alexfernandez Thanks for implementing my requested change. Everything is working as expected.
