### ISSUE TITLE
Multiple query params not supported from the command line

### ISSUE THREAD

**Issue by JesseDavid** [alexfernandez/loadtest#113]
I'm trying to run from the command line for a service that requires multiple query params, but loadtest doesn't seem to support this (or I wasn't able to find the proper syntax for this). I'm trying:

```
loadtest -c 1 -n 1 --rps 1 http://localhost:5000?c=something&p=home
```

When I get see the request come into the server, It displays the input url as `http://localhost:5000?c=something`. Am I missing something from my syntax?

**Comment by alexfernandez** [comment]
You should see the URL it is using in the stats:

    [...] INFO Target URL:          http://localhost:7357?c=something

Try quoting the URL:

    loadtest -c 1 -n 1 --rps 1 "http://localhost:5000?c=something&p=home"

If you are on a Bash console, it is interpreting the `&` to start a new process, and disregarding the `p=home`.

**Comment by JesseDavid** [comment]
@alexfernandez That was my issue, thanks a bunch.
