### ISSUE TITLE
Use Yargs to clean up command line options

### ISSUE THREAD

**Issue by RavenHursT** [alexfernandez/loadtest#118]
While looking into https://github.com/alexfernandez/loadtest/issues/117 I noticed that https://github.com/alexfernandez/loadtest/blob/master/bin/loadtest.js is utilizing a _lot_ of custom logic to manage command line args, enforcing dependancies between them, help messages, etc.

Pretty much all of this can be _greatly_ simplified by just using something like http://yargs.js.org/ ?

**Comment by alexfernandez** [comment]
I am using [stdio](https://www.npmjs.org/package/stdio) to manage options, do you think it is worth it? If so, just send a PR and I will review it.

**Comment by RavenHursT** [comment]
Roger that.. I've used yargs in a lot of projects.. I'll see if I can't port it and we'll see if you like :-)

**Comment by RavenHursT** [comment]
Looks like you were completely right.. stdio is doing essentially the same thing as yargs.. Gonna close this..

**Comment by alexfernandez** [comment]
Thanks for the confirmation. Feel free to work on other areas of loadtest.
