### ISSUE TITLE
How is concurrency/-c related to --rps? 

### ISSUE THREAD

**Issue by gempesaw** [alexfernandez/loadtest#126]
Hi, thanks for putting together this tool! It's been pretty useful to me, so I'm very grateful. I'm curious about how concurrency interacts with the rps setting: what's the difference on the server side between

    loadtest -c 10 --rps 10
    loadtest -c 1 --rps 10

Will the server under test still see 10 rps in both of these cases? Is the load profile that the server under test receives any different? In both cases, are the requests sent without necessarily waiting for a response from the server, to maintain the goal RPS? I feel like I may be missing/misunderstanding something here...

Thanks!

**Comment by alexfernandez** [comment]
Hi, concurrency `-c`is the number of threads used by loadtest, while `--rps` is the number of requests per second sent. If one thread is not enough to keep up with 10 rps (i.e. if each request takes more than 1/10th of a second), then loadtest will send less than 10 rps. With `-c 10` you will need requests to take less than 1 second to keep up with `--10 rps`. Concurrency should be enough to keep up with the desired rps rate; above that there is no benefit, and just a small memory penalty.

HTH, Alex.

**Comment by gempesaw** [comment]
Ah, so ideally I would have some idea of the response time duration and then I'd scale my concurrency to ensure that `loadtest` can send the appropriate constant goal  rps. Thanks, that's very helpful! Cheers c:
