### ISSUE TITLE
unable to terminate process

### ISSUE THREAD

**Issue by mnmkng** [alexfernandez/loadtest#136]
Hi, I ran loadtest from bash on MacOS Sierra 10.12.6 with `-c 1000 -rps 1000`
on a localhost server, and the process couldn't be terminated using control + C. Even though terminal seemed to act normally and returned command line access back, the process kept running underneath and logging output. I eventually had to kill it using Activity Monitor. 

Am I missing some quit command that needs to be run?

**Comment by alexfernandez** [comment]
Hi, sorry for the delay! I just tested with the latest 2.3.0 on MacOS 10.12.6 and it works fine for me. Can you please verify the version with:

```
loadtest --version
```

and report back? Thanks!

**Comment by mnmkng** [comment]
Hello, and sorry for the delay! :) I'm running loadtest 2.3.0. Unfortunately, I'm currently unable to try again, as my server is split in a million pieces in preparation for a major release. I'll try again after the release. Is there anything that might help troubleshoot?

**Comment by alexfernandez** [comment]
@mnmkng Sorry too! :) Just let me the exact command you are using, to see if I can replicate it. Thanks!

**Comment by alexfernandez** [comment]
Hi again, can you please retry with 3.0.0, just published?

**Comment by alexfernandez** [comment]
I guess this should be fixed now with `3.0.2`. Closing, please reopen if needed.

**Comment by mnmkng** [comment]
Hi Alex, it really seems to work as expected now. Great job! Thanks.
