### ISSUE TITLE
take code-splitting into account?

### ISSUE THREAD

**Issue by begoat** [alexfernandez/loadtest#140]
I have a question that whether this tool take code-splitting into account?
will it automatically download chunk files when they do request to certain endpoint?

**Comment by alexfernandez** [comment]
Hi, sorry for the delay. I believe it will, it supports chunked input.

**Comment by begoat** [comment]
Ok thank u


Sent from myMail for iOS


Saturday, 30 December 2017, 6:20 PM +0800 from notifications@github.com  <notifications@github.com>:
