### ISSUE TITLE
Adding --rps seems to only make a single request no matter the other arguments

### ISSUE THREAD

**Issue by lostpebble** [alexfernandez/loadtest#144]
Hi there,

I've been trying to run loadtest in various ways using `--rps` to limit the calls to me test server (which has a rate limiter), this is one way I've tried:

```
loadtest http://localhost:8080 -c 1 -n 50 --rps 0.5
```

I would expect that this would now hit my server 50 times with a request per second rate of 0.5. But this seems to only make a single request and then stops.

I've tried it in other various combinations too, but no matter what I try, using `--rps` seems to only send out a single request and then stop.

**Comment by lostpebble** [comment]
I just down graded to version `2.3.0` and can confirm that it works as expected in that version, so I think this may be an issue with the new `3.0.0` version then.

**Comment by alexfernandez** [comment]
Found it and fixed, please try `3.0.2` just published. Thanks!

**Comment by lostpebble** [comment]
Just updated and tried out `3.0.2` and seems to be working as expected now, thanks @alexfernandez !
