### ISSUE TITLE
Error while running with karma.

### ISSUE THREAD

**Issue by lakshmananmurugesan** [alexfernandez/loadtest#146]
@alexfernandez Please review the attached screenshot. Can you suggest a test runner for loadtest?
<img width="954" alt="screen shot 2018-04-19 at 3 47 02 pm" src="https://user-images.githubusercontent.com/8625480/38986298-a6397408-43e9-11e8-8c82-ea871497a5b8.png">

**Comment by lakshmananmurugesan** [comment]
@alexfernandez Waiting for your input on this.

**Comment by alexfernandez** [comment]
I'm a bit rushed today, will look at it on the weekend. Thanks for your patience!

**Comment by lakshmananmurugesan** [comment]
@alexfernandez Yes, I am running it under chrome headless with Karma. Is this fine or do you suggest something else? 

Following are our doubts:
*What is the difference in max request between one we are setting in options and one we are seeing in test result as totalRequests? We are seeing varied max requests.
Eg. We set in option as 1000 rps with 40 concurrency. In latency result, we are seeing totalRequests as 974. see screenshot. What is the reason?
*Also please explain the test result terms like  percentiles, minLatency etc. Can we see the error msgs from test result?
<img width="448" alt="screen shot 2018-04-23 at 2 31 08 pm" src="https://user-images.githubusercontent.com/8625480/39116878-2845aa22-4703-11e8-882f-79e018fa0ce6.png">

**Comment by lakshmananmurugesan** [comment]
@alexfernandez I want to followup on this. Thank you

**Comment by lakshmananmurugesan** [comment]
@alexfernandez Okay, thanks for your input.
