### ISSUE TITLE
Does this tool support to load test async?

### ISSUE THREAD

**Issue by DuoyueBa** [alexfernandez/loadtest#149]
Now we need to load test async requests. After test client calls server, server will return a response immediately. Then server will do some tasks for this request. After tasks are finished, server will send a response to test client again.

Only when the second response is received, whole test process is completed.

Could you tell us whether there is a simple way to implement this by this tool? Thank you!

**Comment by alexfernandez** [comment]
Hi, it can be done with a [request generator](https://github.com/alexfernandez/loadtest#requestgenerator). I am not sure that qualifies as "a simple way" though :(

**Comment by rgavinc** [comment]
I found a simple way to do this:
`  const result = await new Promise((resolve, reject) => {
    loadTest(options, async (error, result) => {
      if (error) reject(error);
      resolve(result);
    });
  });

  console.info(result);`
