### ISSUE TITLE
Extra requests when concurrency > 1

### ISSUE THREAD

**Issue by iaaly** [alexfernandez/loadtest#152]
Execute this command:
>loadtest -c 10 -n 1000 http://localhost:8080

Check the logs, the number of requests received is 10009.

Here we got an extra 9 = 10 - 1 requests.
In a general case, the number of extra requests is equal to (C-1) where C is the concurrency number.

**Comment by alexfernandez** [comment]
This is a [known issue](https://github.com/alexfernandez/loadtest/issues/130), it should not be hard to solve for what I know. Any takers?

**Comment by charlieknoll** [comment]
I have submitted [pull request 170](https://github.com/alexfernandez/loadtest/pull/170) to address this issue.

**Comment by alexfernandez** [comment]
Merged as loadtest@3.0.9, please verify.
