### ISSUE TITLE
how to send file 

### ISSUE THREAD

**Issue by Manjukb** [alexfernandez/loadtest#156]
in postman its -p file@filename.gz how to do it here

**Comment by Manjukb** [comment]
it takes it as body ??  

in postman if I send -p file@filename.gz  in endpoint req obj  I can access files in req.file.files 

but i can do it here am i missing some thing ??

**Comment by alexfernandez** [comment]
You need to enter the whole path to the file you want to send.

**Comment by alexfernandez** [comment]
Closing, please reopen if needed.
