### ISSUE TITLE
Make default values clearer

### ISSUE THREAD

**Issue by taylorjdawson** [alexfernandez/loadtest#163]
It would be nice to more clearly specify default values for the options. 

For instance the default value for `concurrency` is `1`. I know that not because of the README but because of [this line](https://github.com/alexfernandez/loadtest/blob/de11be61b668291483e10f83603a6ecf5f1d08e2/lib/loadtest.js#L55). Obviously it wasn't too much trouble to determine this but I think it would be nice to have the default values clearly listed alongside their descriptions. 

I could do a PR if you find this helpful.

Thanks! 👍

**Comment by alexfernandez** [comment]
Please do a PR! :clap:
