### ISSUE TITLE
Cannon install using `npm install -g loadtest`

### ISSUE THREAD

**Issue by Lilly2016** [alexfernandez/loadtest#164]
on Windows10
 i run this `npm install -g loadtest`

and get this error

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools v
ersions are "14.0", "4.0".

**Comment by alexfernandez** [comment]
Hi @Lilly2016, I am not sure what that error is about. Maybe someone else here can help you?

**Comment by Kacppian** [comment]
Could this help you - https://github.com/chjj/pty.js/issues/60#issuecomment-284125481

The solution suggested there is - 

open up a new cmd as administrator and run this command:
`npm install --global --production windows-build-tools`
then
`npm config set msvs_version 2015 --global`
close all instances of shell/cmd, reopen a cmd (regular this time, non-administrator) return to your directory where you are trying to run `npm install` and run it again

**Comment by Lilly2016** [comment]
Awesome! thanks guys, that works.

**Comment by alexfernandez** [comment]
Thanks! Closing, please reopen if needed.
