### ISSUE TITLE
Typings issue: timeout should be with lowercase

### ISSUE THREAD

**Issue by hodbauer** [alexfernandez/loadtest#166]
https://github.com/alexfernandez/loadtest/blob/19b7885880a239f79932a2da0ddcdb04e12de5dc/index.d.ts#L9
According to the line above timeout option is written `timeOut`.
But inside the code there is only `timeout`.
So if i'm using typescript i will run forever because there is no timeout...

**Comment by alexfernandez** [comment]
Probably a typo, care to send a PR?

**Comment by hodbauer** [comment]
Fixed
