### ISSUE TITLE
Docs say there should be an errors property in result, but it's really errorCodes

### ISSUE THREAD

**Issue by jodymgustafson** [alexfernandez/loadtest#179]
According to the docs and the typedef file, the LoadTestResult object should have an **errors** property, but it's really called **errorCodes**. This is what the result object looks like:

`{"totalRequests":5,"totalErrors":5,"totalTimeSeconds":4.3027839000000005,"rps":1,"meanLatencyMs":179,"maxLatencyMs":302,"minLatencyMs":122,"percentiles":{"50":134,"90":302,"95":302,"99":302},"errorCodes":{"401":5},"instanceIndex":0}`

**Comment by alexfernandez** [comment]
Well seen! Corrected in https://github.com/alexfernandez/loadtest/commit/85b1a1f17027f3fb7fcba9bef3befd9f9616cede, published as 5.0.2. Thanks! :+1: 

Closing, please reopen if needed.
