### ISSUE TITLE
Using an elapsed time from the response payload

### ISSUE THREAD

**Issue by haganbt** [alexfernandez/loadtest#182]
I would like to be able to use a value returned in a response to overwrite the elapsed time.

I need to measure an execution time that occurs on the server, rather than the time of the full request.

Can I overwrite the `result` object in any way? Testing within the `statusCallback()` function but I cannot get it to work.

Appreciate any guidance.

**Comment by alexfernandez** [comment]
To be honest, `loadtest` was not designed with this purpose in mind. I would suggest returning this server time in a JSON and processing it in an _ad hoc_ client.

**Comment by haganbt** [comment]
Thanks for the confirmation. I expected that to be the case but wanted to make sure I was not missing anything.

I will extract and mange the results manually.

Thank you for your open source work. Super helpful tool.

**Comment by alexfernandez** [comment]
Thanks a lot! Much appreciated ^_^
