### ISSUE TITLE
Request Generator supposed to return request object

### ISSUE THREAD

**Issue by zzxoto** [alexfernandez/loadtest#188]
The request generator provided in the options is supposed to return request object (as seen in the line 190 - 193 in the httpClient.js). However this fact is missing (or outdated) in the markdown documentation. The documentation instead has the following: 

```
module.exports = function(params, options, client, callback) {
  generateMessageAsync(function(message) {
 
    if (message)
    {
      options.headers['Content-Length'] = message.length;
      options.headers['Content-Type'] = 'application/x-www-form-urlencoded';
    }
    request = client(options, callback);
    if (message){
      request.write(message);
    }
 
    return request;
  }
}
```

Package version: "5.0.4"

**Comment by alexfernandez** [comment]
Well seen! Care to send a pull request? :wink:

**Comment by zzxoto** [comment]
On it.

**Comment by alexfernandez** [comment]
What do you think is more useful? I would think that changing the documentation would be best.

**Comment by zzxoto** [comment]
I will get back at this with a well thought out answer, might take as long as a week though.
