### ISSUE TITLE
Passing statusCallback to the UI

### ISSUE THREAD

**Issue by dbybanez** [alexfernandez/loadtest#189]
Hello, I was looking for a way to test API endpoints and I came across loadtest package (I don't know if I'm on the right path). I'm using the loadtest API and I successfully used it in my Node application. Now, my question is, how can I utilize statusCallback so I can show "live" updates to the UI? In the example, it only console.logs it. Thanks! And awesome work! 

PS: I'm a newbie to Node.

**Comment by dbybanez** [comment]
Nevermind. I've done it. Sorry for being dumb. Lol. And thanks again for the package! It really helped me on my school! 😊

**Comment by alexfernandez** [comment]
No problem, glad it works for you! :+1: Anything else, feel free to open another issue.
