### ISSUE TITLE
:"Error: MultipartParser.end(): stream ended unexpectedly: state = START_BOUNDARY

### ISSUE THREAD

**Issue by harshsharma22** [alexfernandez/loadtest#193]
loadtest -m POST -p '/home/test.pdf' -T "multipart/form-data; boundary='---WebKitFormBoundary7MA4YWxkTrZu0gW---'"

**Comment by alexfernandez** [comment]
Sorry for the delay. It looks like the URL isn't working, right?

**Comment by alexfernandez** [comment]
Closing for now; please reopen if necessary.
