### ISSUE TITLE
Requests per second is more than Max Request on my linux machine.

### ISSUE THREAD

**Issue by Creatoon** [alexfernandez/loadtest#197]
Why my request per second is more than the maximum requests?

![Screenshot from 2021-06-09 12-08-35](https://user-images.githubusercontent.com/65965202/121305844-b56c3680-c91b-11eb-946b-4f3c1829630c.png)

**Comment by alexfernandez** [comment]
It makes sense. Imagine you send 1000 requests in 0.1 seconds; you would be sending 10000 requests per second (if you continued for 0.9 more seconds) :thinking:
