### ISSUE TITLE
node:events:505  throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by sahinrasit** [alexfernandez/loadtest#205]
C:\Users\90555>testserver-loadtest
[Tue Apr 26 2022 17:16:26 GMT+0300 (GMT+03:00)] INFO Listening on port 7357
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at tryReadStart (node:net:620:20)
    at WriteStream.Socket._read (node:net:631:5)
    at WriteStream.Readable.read (node:internal/streams/readable:496:27)
    at WriteStream.Socket.read (node:net:672:39)
    at resume_ (node:internal/streams/readable:1010:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4053,
  code: 'ENOTCONN',
  syscall: 'read'
}

**Comment by rahul1235** [comment]
+1

**Comment by VasilNikolov** [comment]
+1

**Comment by mugavri** [comment]
+1

**Comment by Nishant-Chorge** [comment]
+1

**Comment by fardeen85** [comment]
+1

**Comment by lRafaelOliveira** [comment]
+1

**Comment by Prakash-Reddy08** [comment]
facing same issue

**Comment by undermuz** [comment]
+1

**Comment by yurigo** [comment]
+1

**Comment by alexfernandez** [comment]
It works correctly for me (Ubuntu Linux). How or when are you getting this error?

**Comment by alexfernandez** [comment]
OK, I think I have an idea of where this is coming: catch errors on the incoming requests.
  https://github.com/alexfernandez/loadtest/pull/216

The error comes from an unhandled error event, and I see that errors in the server and in the socket are caught, so my hypothesis is that request errors are to blame. Also `ENOTCONN` seems to be that the connection was closed from the other side.

I'm not sure though. I'm not on Windows and have never seen this error. So if you could test v6.3.1 and check if the error is gone, that would be great. Thanks!

**Comment by alexfernandez** [comment]
If you still see this error, please reopen.
