### ISSUE TITLE
LoadRunner

### ISSUE THREAD

**Issue by mobinajawahar** [alexfernandez/loadtest#206]
The[ LoadRunner Training in Chennai ](https://chennaitraining.in/load-runner-training-in-chennai/)at IntelliMindz Academy permits the members to have the most publicity to the LoadRunner Architecture, Environment, Components, and superior ideas like VUser, VUGen, below the Mentorship of Testing Experts from the Industry. We are the exceptional education Institute that affords certification-oriented LoadRunner Training in Chennai. Our Training will be targeted at helping in placements as well. We have separate HR group gurus who will take care of all your interview needs. [LoadRunner](https://en.wikipedia.org/wiki/LoadRunner) is a Performance trying out device that helps a number of improvement tools, applied sciences, and communication protocols. LR is the sole device in the market that approves a giant variety of protocols to do overall performance testing. For more information contact us on 9655877677.

**Comment by alexfernandez** [comment]
Spam.
