### ISSUE TITLE
Cannot find package microprofiler imported from /node_modules/loadtest/lib/parser.js

### ISSUE THREAD

**Issue by shoaib9121** [alexfernandez/loadtest#224]
In node js app, Getting error `Cannot find package microprofiler imported from /node_modules/loadtest/lib/parser.js`. Tried installing `loadtest` locally, globally. None have worked. 

/package.json
```
"scripts": {
    "loadtest": "npx loadtest -n 1200 -c 400 -k http://localhost:3000/"
  },
```

**Comment by alexfernandez** [comment]
Sorry, that was a bit of testing code that should never have reached production. Removed now!

Fixed in v8.0.2 just released. Thanks for the report!
