### ISSUE TITLE
Concurrent Clients mismatch

### ISSUE THREAD

**Issue by emil916** [alexfernandez/loadtest#226]
After updating loadtest, I am seeing a different value for CC in the end results.  See below:

loadtest -t 5 **_-c 25_** --rps 1000 "http://localhost:30000/fib?30"

Target URL:          http://localhost:30000/fib?30
Max time (s):        5
Target rps:          1000
**_Concurrent clients:  23_**
Running on cores:    4
Agent:               none

Completed requests:  4999
Total errors:        2
Total time:          5.182 s
Mean latency:        3.7 ms
Effective rps:       965

Percentage of requests served within a certain time
  50%      3 ms
  90%      5 ms
  95%      7 ms
  99%      12 ms
 100%      30 ms (longest request)

   -1:   2 errors

**Comment by alexfernandez** [comment]
Keep in mind that the latest version is creating concurrent clients on demand; if it cannot create 25 clients in the five assigned seconds it will report less, as in your case. Can you try with a longer time to see if it reaches 25? Thanks!

**Comment by alexfernandez** [comment]
Oh, you are right! I did not notice the `--rps` above. Actually it's explicitly mentioned in the documentation:

```
Note: the `--concurrency` option will be ignored if `--requestsPerSecond` is specified;
clients will be created on demand.
```

**Comment by emil916** [comment]
Oh, then my bad. Is it a new thing or was it like this since old times? (I dont have the most update version yet).

I think this Note should be shown as a warning when one uses both options anyways.

**Comment by alexfernandez** [comment]
It's a new thing for versions 8+ I think. Instead of showing the warning I opted for displaying the actual number of concurrent clients, perhaps it could be made more evident :thinking:

**Comment by emil916** [comment]
Alright, it all make sense now. Thanks! Closing the issue.
