### ISSUE TITLE
Number of total requests is incorrect

### ISSUE THREAD

**Issue by fetis** [alexfernandez/loadtest#238]
I execute this command 
```
npx loadtest -t 5 -c 25 http://localhost:8080/public-api/xxx
```

and `loadtest` reports to me about 359 completed requests, but in reality when I check my server logs I see that total amount of requests were 509

I'm using v8

Full output
```
Max time (s):        5
Concurrent clients:  150
Running on cores:    6
Agent:               none

Completed requests:  359
Total errors:        0
Total time:          6.409 s
Mean latency:        1629 ms
Effective rps:       56
```

**Comment by alexfernandez** [comment]
Hi @fetis , the number of actual requests may be higher when limited by time, as there may be inflight requests at the time of stopping.
