### ISSUE TITLE
Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

### ISSUE THREAD

**Issue by nelisbijl** [alexfernandez/loadtest#35]
Hi,

I encountered above warning multiple times when running loadtest. Usually followed by:
RangeError: Maximum call stack size exceeded

This occurs when the server starts returning errors (my hypothesis). It causes a stacking of nextTick calls in node's core libraries http, net and dns. 
I could avoid this by adding a setImmediate in getRequestFinisher:

            setImmediate(function () {
                operation.callback(error, result, callback);
            });

I don't have the time to sort out whether this is the right place or whether Node should live up to their own warning. I just know that it cures the problem.

**Comment by alexfernandez** [comment]
I'm closing this report since it's a bit old. Please reopen if still an issue.
