### ISSUE TITLE
Does Your Module Support Multi-Part/FormData 

### ISSUE THREAD

**Issue by weezyboyaxy** [alexfernandez/loadtest#43]
First of all Bunch of thanx to @alexfernandez  for developing this module !

Secondly can i use Multi-Part/FormData instead of application/x-www-form-urlencoded ?!

If so , then how can i give  or how do i insert a file in body !

Or this module doesn't Support -> Multi-Part/FormData ?

**Comment by alexfernandez** [comment]
Right now `loadtest` does not support multipart/form-data, sorry. Patches welcome :)

**Comment by weezyboyaxy** [comment]
thank you ..... you can close my issue :)

**Comment by weezyboyaxy** [comment]
And can you suggest me , which module does support loadtest for  multipart/formdata !

**Comment by alexfernandez** [comment]
Sure, the function that makes the request is [`makeRequest`](https://github.com/alexfernandez/loadtest/blob/master/lib/loadtest.js#L154) in `loadtest.js`.

**Comment by automata** [comment]
@alexfernandez I tried to use `requestGenerator` to send multipart/form-data through:

```coffeescript
        requestGenerator: (params, opts, client, callback) ->
          opts.headers = formData.getHeaders()
          request = client opts, callback
          formData.pipe request
          request.on 'response', (res) ->
            console.log 'response'
          request.on 'error', (err) ->
            console.log 'error', err
          request.end()
```
However I'm getting that the stream ended unexpectedly on the server. Does it makes sense? Maybe loadtest is breaking the stream trying to keep track with timing?

Otherwise I'm planning to take a look in `makeRequest` and try to get multipart there.

**Comment by alexfernandez** [comment]
I am not sure since I am just using `http.request()` to send data, maybe this library (or its `https` counterpart) is doing weird stuff with the request.

**Comment by automata** [comment]
It seems that https://github.com/alexfernandez/loadtest/blob/master/lib/loadtest.js#L254 doesn't implements `on 'request'`, so we can't pipe to that. I'm trying something around that.
