### ISSUE TITLE
-R requestGeneratorModule.js does not work

### ISSUE THREAD

**Issue by anfedorov** [alexfernandez/loadtest#44]
it appears to be only partially implemented, and the example doesn't work. it seems as if it would be easiest to get it working using the library and providing an example of that.

**Comment by alexfernandez** [comment]
It should be complete, but perhaps the explanation (and the example) are not very good. How would you improve it?

**Comment by pputhran** [comment]
perhaps a detailed example of how to use it would help.

**Comment by tangxinfa** [comment]
I make a pull request to fix this bug.

And here is a  example module do nothing but works:

module.exports = function(params, options, client, callback) {
    request = client(options, callback);
    if (params.timeout) {
        request.setTimeout(params.timeout, function() {
            requestFinished('Connection timed out');
        });
    }

    var message = '';

    // Generate your message(request body) here.

    if(message) {
        request.write(message);
    }

    request.on('error', function(error) {
        requestFinished('Connection error: ' + error.message);
    });

    request.end();
};

**Comment by pputhran** [comment]
Sorry, I am newbie to NodeJS, This is what I have in my loadtest.js

var loadtest = require('loadtest');
var request = require('./request.js');
var options = {
    url: 'http://HOSTNAME:3000/ingest',
	method: 'POST',
	maxRequests: 1,
	contentType:'application/json',
	agentKeepAlive:'true',
	requestGenerator:request("10",options)
	};
loadtest.loadTest(options, function(error, result)
{
    if (error)
    {
        return console.error('Got an error: %s', error);
    }
    console.log('Tests run successfully');
	console.log(result)
});

Request.js:

	module.exports = function(params, options, client, callback) {
    request = client(options, callback);
    if (params.timeout) {
        request.setTimeout(params.timeout, function() {
            requestFinished('Connection timed out');
        });
    }

    var message = '{"customerID":"9562ee81-7e2d-4678-80cc-b24c732c5f45","siteID":"12d4d9f4-457a-477e-8cfe-792429af8dde","equipmentID":222,"time":"ba8e0a83-c7b0-11e4-995d-f72810bc1ef7","value":121.55,"uom":"psi","countHandle":0}';

    // Change message(request body) or options here.

    if(message) {
        request.write(message);
    }

    request.on('error', function(error) {
        requestFinished('Connection error: ' + error.message);
    });

    request.end();
};

end up getting the below error:

c:\LoadTest>node loadtest.js
c:\LoadTest\request.js:3
    request = client(options, callback);
              ^
TypeError: undefined is not a function
    at module.exports (c:\LoadTest\request.js:3:15)
    at Object.<anonymous> (c:\LoadTest\loadtest.js:9:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by alexfernandez** [comment]
I have added a [complete sample](https://github.com/alexfernandez/loadtest/blob/master/lib/request-generator.js) as requested by @anfedorov, hopefully it will help @pputhran also.

Along with @tangxinfa 's PR this issue should be solved now. Please reopen if you find any further problems.

**Comment by anfedorov** [comment]
awesome, thanks so much!
