### ISSUE TITLE
maxLatencyMs not in results

### ISSUE THREAD

**Issue by cspiegl** [alexfernandez/loadtest#45]
I was wondering why the maxLatencyMs is not in the results object (and the percentiles only provide 50, 90, 95 and 99 values).

Could this be added easily?

**Comment by alexfernandez** [comment]
Yes, surprisingly easily! Added in commit 6b0e65d1d6d01b5df85e4495525c8f1319284b0f for version 1.2.7, please check that it works properly for you.

**Comment by cspiegl** [comment]
Thank you, it works like a charm. 

Maybe also update the Readme so that people know it is there:

https://github.com/alexfernandez/loadtest/blob/master/README.md#results

**Comment by alexfernandez** [comment]
Great idea, thanks.
