### ISSUE TITLE
Worst performance results than ab

### ISSUE THREAD

**Issue by jgato** [alexfernandez/loadtest#47]
Hi there,

I need to make really hard performance test against a node with express services. Doing an initial test against a hello world service I have very significant differences between using loadtest and the traditional ab:

With loadtest:

```
>loadtest -n 50000 -c 1000 http://localhost:3000/version

[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO 
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO Target URL:          http://localhost:3000/version
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO Max requests:        50000
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO Concurrency level:   1000
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO Agent:               none
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO 
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO Completed requests:  50000
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO Total errors:        0
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO Total time:          43.307403647 s
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO Requests per second: 1155
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO Total time:          43.307403647 s
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO 
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO Percentage of the requests served within a certain time
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO   50%      538 ms
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO   90%      1373 ms
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO   95%      1527 ms
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO   99%      7267 ms
[Fri Feb 27 2015 19:00:53 GMT+0100 (CET)] INFO  100%      31354 ms (longest request)

```
The same test but using ab:

 ```
)>ab -n 50000 -c 1000 -k http://localhost:3000/version
This is ApacheBench, Version 2.3 <$Revision: 1528965 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/
Concurrency Level:      1000
Time taken for tests:   22.181 seconds
Complete requests:      50000
Failed requests:        0
Keep-Alive requests:    0
Total transferred:      25450000 bytes
HTML transferred:       3650000 bytes
Requests per second:    2254.14 [#/sec] (mean)
Time per request:       443.629 [ms] (mean)
Time per request:       0.444 [ms] (mean, across all concurrent requests)
Transfer rate:          1120.46 [Kbytes/sec] received


Percentage of the requests served within a certain time (ms)
  50%    119
  66%    138
  75%    158
  80%    180
  90%   1127
  95%   1164
  98%   3133
  99%   3322
 100%  15219 (longest request)
```

Is it normal so big differences for the same test?

**Comment by alexfernandez** [comment]
Sadly, yes. The precision of `loadtest` is quite poor above a few krps (1000's of requests per second), since much of the processing time is used by `loadtest` itself, in particular by the HTTP library. It is explained a bit in the README, although the numbers there may be a bit optimistic (it says ~4000 requests per second). There you can see how to estimate if `loadtest` is a good option.

I have plans to use barebones sockets, which should increase performance drastically, but have not got around to it yet.

What are your specs?

**Comment by jgato** [comment]
I need to create some incremental/configurable tests. Regarding a configuration I prepare a battery of tests that I need to execute (10 times 100rps 100 clients, 10 times 300rps 100 clients, and so on and so on). I need something "programatically" and using node.js, that is the reason of using loadtest. But if the results are not real enough, I fear I would need other option. It is a pity, because the usability of your library is really cool!!!

**Comment by alexfernandez** [comment]
Are you on Windows? What kind of hardware do you have? Is your software CPU-bound? You can check out how much CPU `loadtest` is using when testing and report back; if it's around 100% there is not much that can be done right now.

In my limited experience, for programmatic load tests what matters is not the absolute results but to set a baseline, so that if performance drops below a certain threshold test fail. But your scenario may be different.

**Comment by jgato** [comment]
It is taking almost 100% of CPU. My hardware is i5 6GB RAM and unbutu 14.04.

**Comment by alexfernandez** [comment]
Hum, it should get to quite a bit higher. Sadly I don't think there is much to do but to use sockets directly. I hope you can still use it as a baseline.

**Comment by jgato** [comment]
Thanks @alexfernandez I will see what I can do.

**Comment by jgato** [comment]
Another estrange issue that I am suffering. After some hard tests (even using command line) when everything is finished, the process is still waiting before returning the prompt. Like if it was waiting for closing connections. But all the results have been showed

**Comment by alexfernandez** [comment]
Yes, this is a known issue. The loadtester is just waiting for the connections to time out, which they do in a little while.

**Comment by jgato** [comment]
Or even hours after 30 minutes of continuos testing ;)

**Comment by alexfernandez** [comment]
Well, that is _not_ a known issue! Let's open a new issue to investigate.
