### ISSUE TITLE
Process not finishing

### ISSUE THREAD

**Issue by alexfernandez** [alexfernandez/loadtest#48]
Reported by @jgato: "After some hard tests (even using command line) when everything is finished, the process is still waiting before returning the prompt. Like if it was waiting for closing connections. But all the results have been showed." Apparently the process does not ever end.

Can you try cloning the repo and running `npm test` to see if it ends in your setup?

**Comment by jgato** [comment]
Some more Info: With a node.js script, after the execution of several
loadtest calls (I do this syncrhonous, async.series) the process takes too
much time to finish. Actualy, after all the tests are finished (and the
process is trying to finish) I try to write some results in a file, and
this is blocked it does not happens. Maybe something is blocking the node
event's queue? As a workaround, now I write results to file synchronous,
so, I can see the results in the file, while I wait for the process to
finish.

I will run npm test tomorrom morning :)

**Comment by jgato** [comment]
I have run npm test without problems, but this waiting to finish around 10 seconds.

**Comment by MyLittleRobo** [comment]
For me the process ends, but has significant freeze after finishing all tests (like for 3 seconds or more). Both when I start npm test for loadtest or use loadtest in my application.

**Comment by alexfernandez** [comment]
No longer an issue, and I haven't found the reason for the freeze. Closing, please reopen if needed.
