### ISSUE TITLE
-c concurrency should be renamed -p parallel

### ISSUE THREAD

**Issue by the1mills** [alexfernandez/loadtest#52]
if these requests are truly happening *simultaneously*, then those are parallel processes, not concurrent ones.

it might be too late to change your library

check this out

http://stackoverflow.com/questions/1050222/concurrency-vs-parallelism-what-is-the-difference

my guess is that your library is truly concurrent not parallel, so maybe you should revise the word "simultaneous"

**Comment by alexfernandez** [comment]
Good catch. Clarified in commit b9674af, feel free to reopen if you think it's not clear enough.
