### ISSUE TITLE
Loadtest can't handle redirects

### ISSUE THREAD

**Issue by devlato** [alexfernandez/loadtest#54]
Hi, 
I'm trying to test one service and loadtest fails  to load required response because it receives 302 HTTP Code, here are some log records from verbose mode: 

[Fri May 01 2015 15:04:11 GMT+0300 (MSK)] DEBUG Initializing histogram for 1434
[Fri May 01 2015 15:04:11 GMT+0300 (MSK)] DEBUG Total requests 78, max requests: undefined
[Fri May 01 2015 15:04:11 GMT+0300 (MSK)] DEBUG HTTP client connected to http://localhost/light/common with id d2f445d1be267c024a8bee628ab53b97ce60914a9564d2046288213b67489f0c
[Fri May 01 2015 15:04:11 GMT+0300 (MSK)] DEBUG Connection d2f445d1be267c024a8bee628ab53b97ce60914a9564d2046288213b67489f0c failed: Status code 302
[Fri May 01 2015 15:04:11 GMT+0300 (MSK)] DEBUG New value: 1488.4629810000001
[Fri May 01 2015 15:04:11 GMT+0300 (MSK)] DEBUG Partial requests: 79
[Fri May 01 2015 15:04:11 GMT+0300 (MSK)] DEBUG Initializing histogram for 1488

Is it possible to pass any options to force redirect handling?

**Comment by alexfernandez** [comment]
Not currently, but it should not be hard to handle the redirect; I'm doing that currently in my package basic-request. Do you think it's worthwhile to add it? Since you can just test the redirected URL.

**Comment by alexfernandez** [comment]
Closing, please reopen if still an issue.
