### ISSUE TITLE
Query (URL params)

### ISSUE THREAD

**Issue by MyLittleRobo** [alexfernandez/loadtest#55]
Is it possible to set query params for request? It's not flexible to add these params to URL itself.

**Comment by alexfernandez** [comment]
Can you give an example? I'm not sure I understand what you want to do.

**Comment by MyLittleRobo** [comment]
I mean [Query string](http://en.wikipedia.org/wiki/Query_string). This is the part of URL of course, but it still would more convenient to keep them separate (as an assotiative array, for example) from the base uri and then automatically apply url encoding and concatenate.

**Comment by alexfernandez** [comment]
I understand that this issue can be closed, please reopen if necessary.
