### ISSUE TITLE
URL generator

### ISSUE THREAD

**Issue by MyLittleRobo** [alexfernandez/loadtest#56]
So there's request generator, but no url generator.
In REST API the common practice is to use params from endpoint itself (like /resources/resourceID where's resourceID is different for every single resource). The lack of url generator makes it impossible to test REST servers.

**Comment by alexfernandez** [comment]
You are right, I suggest that you propose a PR to improve the situation.

**Comment by alexfernandez** [comment]
I'm closing this issue, please reopen if necessary.
