### ISSUE TITLE
Requests with empty body when using requestGenerator

### ISSUE THREAD

**Issue by MyLittleRobo** [alexfernandez/loadtest#57]
I wrote simple express application and loadtest for it. https://github.com/MyLittleRobo/loadtesttest
The problem is that some number of first requests always have empty body. Server returns BadRequest if request does not have "data" field. Tests show that the number of bad requests is always equal to number of concurrent clients.

Tested on Windows 8 and Mac OS X.

Probably I did something wrong in request generator though. When I use just "body" (not generator) all requests are valid.

**Comment by MyLittleRobo** [comment]
Seems like the fix is to create request object after option headers are set (contrary to examples in README.md).

```javascript
options.headers['Content-Length'] = message.length;
options.headers['Content-Type'] = 'application/json';
var request = client(options, callback);
request.write(message);
request.end();
```

**Comment by alexfernandez** [comment]
Thanks for that! Care to send a pull request?

**Comment by MyLittleRobo** [comment]
Strangely it does not fix lib/request-generator.js test. Should figure out what's wrong with it first.

**Comment by alexfernandez** [comment]
Closing, please reopen if needed.
