### ISSUE TITLE
Post data not sent

### ISSUE THREAD

**Issue by julian-weinert** [alexfernandez/loadtest#59]
I'm trying to test a very simple API that has just one method and two input parameters which needs to be passed as POST.

I use this script to generate the post data:

```javascript
module.exports = function(requestID) {
    // var randomName = ...
    // var randomMail = ...
    return {name: randomName,
            mail: randomMail};
};
```

I'm now calling the API test from the command line:

`loadtest -n 100 -c 10 --rps 100 -H X-Requested-With:API -T multipart/form-data -p postcontent.js http://localhost/API/send/`

My PHP API logs the request using
```PHP
ob_start();
echo "request header\n";
print_r(getallheaders());
echo "\n\nrequest\n";
print_r($_REQUEST);
echo "\n\npost\n";
print_r($_POST);
echo "\n\nget\n";
print_r($_GET);
echo "\n\nserver\n";
print_r($_SERVER);

fwrite($log_file, ob_get_clean());
```

The dumped request is definitely not what I expect:

```
request header
Array
(
    [host] => localhost
    [user-agent] => loadtest/1.2.11
    [accept] => */*
    [x-requested-with] => API
    [Content-Type] => multipart/form-data
    [Content-Length] => 52
    [Connection] => close
)

request
Array
(
)

post
Array
(
)

get
Array
(
)

server
Array
(
    [HTTP_HOST] => localhost
    [HTTP_USER_AGENT] => loadtest/1.2.11
    [HTTP_ACCEPT] => */*
    [HTTP_X_REQUESTED_WITH] => API
    [CONTENT_TYPE] => multipart/form-data
    [CONTENT_LENGTH] => 52
    [HTTP_CONNECTION] => close
    [PATH] => /usr/bin:/bin:/usr/sbin:/sbin
    [SERVER_SIGNATURE] => 
    [SERVER_SOFTWARE] => Apache/2.4.10 (Unix) PHP/5.5.20 OpenSSL/0.9.8zd
    [SERVER_NAME] => localhost
    [SERVER_ADDR] => 127.0.0.1
    [SERVER_PORT] => 80
    [REMOTE_ADDR] => 127.0.0.1
    [REQUEST_SCHEME] => http
    [CONTEXT_PREFIX] => 
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => POST
    [QUERY_STRING] => 
    [argv] => Array
        (
        )

    [argc] => 0
)```

**Comment by dmonay** [comment]
I am facing the same issue. When attempting to load test an endpoint that expects a POST request, the loadtest API sends a POST request but with an empty body.

**Comment by dmonay** [comment]
So it seems like the issue is that I wasn't setting the content-type. And if that's not set, it defaults to 'text/plain'. So this fixed it: options.contentType = 'application/json';

**Comment by alexfernandez** [comment]
Hi @dmonay, can you please send a pull request, so I can merge the fix into the main repository? Thanks!

**Comment by alexfernandez** [comment]
Please try out @khaihkd's new `--method` and `--data` parameters in 1.2.13, and reopen this issue if necessary.
