### ISSUE TITLE
Response object per request

### ISSUE THREAD

**Issue by IRGreg** [alexfernandez/loadtest#60]
Is there a way to view the response object (status code / payload / etc) per request? I know there is the  statusCallback function but that only displays the current stats not the response object.

**Comment by alexfernandez** [comment]
There is not, patches are welcome :)

**Comment by kentmw** [comment]
+1 I know I should push a patch, but I did want to speak up that this would be nice.

**Comment by alexfernandez** [comment]
I have added a second parameter to `statusCallback` as documented in the README in version 1.3.0, please verify that it has what you need.

**Comment by kentmw** [comment]
@alexfernandez thanks, didn't read that part.

**Comment by alexfernandez** [comment]
No wonder, it's a new feature I just released :)
