### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by ehacke** [alexfernandez/loadtest#61]
I'm looking to load test a proxy service that I've built.

Is there any support for routing loadtest requests via a proxy? Any plans for this or thoughts?

**Comment by alexfernandez** [comment]
There are no plans currently, but we value code contributions and try to merge them as fast as possible.

**Comment by ehacke** [comment]
@alexfernandez Ok great, thanks. I'll take a look at what it would require to implement. Thanks.

**Comment by alexfernandez** [comment]
Great! Feel free to ask for help, or reopen the issue if you consider it appropriate.
