### ISSUE TITLE
testing set of different routes/endpoints on a given server

### ISSUE THREAD

**Issue by ORESoftware** [alexfernandez/loadtest#66]
I remember experimenting with this module 6 months ago. What wasn't obvious then, and still isn't obvious, is how you put a load on a server by making requests to a variety of different routes, instead of just a single route/endpoint. Forgiven me if I mistaken, but is this possible with this module? It this easy to set up?

**Comment by alexfernandez** [comment]
Different routes as such are not supported. What you can do is use [`indexParam`](https://github.com/alexfernandez/loadtest#indexparam) to insert an increasing parameter and thus vary the resulting URL.

Needless to say, patches welcome!

**Comment by ORESoftware** [comment]
huh, wouldn't it be relatively easy to add that feature? I will think about adding a patch

**Comment by alexfernandez** [comment]
I agree it should not be hard to do. Please reopen this issue if necessary.
