### ISSUE TITLE
loadtest API callback fired after 1/n client finishes

### ISSUE THREAD

**Issue by sameercaresu** [alexfernandez/loadtest#67]
Simply take a route

      app.get("/testConcurrency", function(req, res){
                // some sql query that can take different time to insert same amount of data
                setTimeout(function(){ res.send("ok"); }, variableTimeout)
      });

And calling loadtest api
    
    var options = {
           url: url,
          "maxRequests": 1,
          "concurrency": 3,
    } 
    loadtest.loadTest(options, function(error, result){
        if(error){
            res.send("Error: " + error);
        }
        // console.log(result);
        // this will send the result from the 1st request
       // hence ignoring the time spent on subsequent concurrent requests
        res.send(result);
    })

Shouldn't "totalTimeSeconds" in result should be sum of all the concurrent requests?

**Comment by alexfernandez** [comment]
In this case you are sending just one request, which is what `maxRequests` specifies. `concurrency` is only used for more than one request.

Please reopen if you have further questions.
