### ISSUE TITLE
total time is always around 64sec

### ISSUE THREAD

**Issue by jsvishal45** [alexfernandez/loadtest#68]
In alll the below cases Total Time is around 64(a fix value) sec with increasing number of failure
loadtest http://localhost:3000/search -n 18 -c 18
loadtest http://localhost:3000/search -n 20 -c 20
loadtest http://localhost:3000/search -n 30 -c 30

Can I extent this time to reduce number of failure

**Comment by alexfernandez** [comment]
Sure, just use the [`-t` timelimit parameter](https://github.com/alexfernandez/loadtest#-t-timelimit).

**Comment by jsvishal45** [comment]
I had tried  -t 180 but same result :(

**Comment by jsvishal45** [comment]
In the example 
loadtest http://localhost:7357/ -t 20 -c 10
how come Total time:          44.503181166000005 s?

**Comment by alexfernandez** [comment]
Because `-t 20` instructs loadtest to stop sending requests after 20 seconds, but responses may keep coming for a few seconds afterwards.

**Comment by alexfernandez** [comment]
If `-t 180` yields the same result, then it may be a problem with the server, not with loadtest.
