### ISSUE TITLE
won't compile

### ISSUE THREAD

**Issue by donniev** [alexfernandez/loadtest#71]
```
donvawter@TheBeast ~> loadtest -c 10 -rps 200 http://localhost:2500
/Users/donvawter/.nvm/versions/node/v0.12.7/lib/node_modules/loadtest/bin/loadtest.js:86
        if (if (method_accept.indexOf(options.method) === -1)){
            ^^
SyntaxError: Unexpected token if
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by donniev** [comment]
```
loadtest@1.2.13 /Users/donvawter/.nvm/versions/node/v0.12.7/lib/node_modules/loadtest
├── agentkeepalive@2.0.3
├── testing@0.2.2
├── log@1.4.0
├── stdio@0.2.7
└── prototypes@0.4.2
donvawter@TheBeast ~> loadtest -c 10 -rps 200 http://localhost:2500
```

**Comment by alexfernandez** [comment]
Argh! Corrected in `loadtest@1.2.14`. Please upgrade and retry, and reopen this issue if necessary.

**Comment by alexfernandez** [comment]
Thanks for reporting it, by the way :)

**Comment by donniev** [comment]
sure.
I had made the change locally because it was pretty obvious :-)
What I really need is a test that can measure how the site behaves under load. You know have 50 browser sessions open and make sure the site doesn’t slow down.
Just making a request to site and getting a response doesn’t really tell me a whole lot since all the heavy lifting is done after the page loads via ajax calls where all the database interaction occurs.
Do you have any suggestions for a tool that can help.
Your tool is essentially testing the ability of node/express to respond to a request and would be important if I had a high volume site but for my use case node just laughs and says “Is that all you got, I can handle that in my sleep”

**Comment by alexfernandez** [comment]
I can't think about anything, I will ask for help on Twitter.

**Comment by alexfernandez** [comment]
You can try with concurrency 50: `-c 50` to simulate 50 browsers requesting at the same time. Would that help?
