### ISSUE TITLE
use different payload for each request

### ISSUE THREAD

**Issue by DannyCork** [alexfernandez/loadtest#76]
I'd like to POST a different payload data for each request e.g.:

{ taskId : "a1",..... }

{taskId : "a2" ,......}

Any advice on how I could achieve this?  Thanks.

**Comment by alexfernandez** [comment]
You can use a [request generator](https://github.com/alexfernandez/loadtest#-r-requestgeneratormodulejs). You have a [sample](https://github.com/alexfernandez/loadtest/blob/master/lib/request-generator.js) that should help you get started.

**Comment by DannyCork** [comment]
thanks. It also looks like the -p POST_file can achieve this.
