### ISSUE TITLE
Use of prototypes can break application behavior during tests

### ISSUE THREAD

**Issue by FrankHassanabad** [alexfernandez/loadtest#77]
Your usage of your prototypes which has:

```
safeParseInt
```

which returns a 0 whenever someone does a 

```
parseInt(undefined);
```

instead of NaN, breaks application tests whenever they pull in your loadTest to use directly as an API.  

I would suggest not using prototypes library within this library since it changes signatures of existing Math packages that already exist in libraries.  

Prototypes also breaks other 3rd party libraries in general by changing those relied upon signatures.

**Comment by alexfernandez** [comment]
Well seen!

In commit b0e7533 I have updated the dependencies to use the latest prototypes which doesn't show this issue, please update to 1.2.15.

And please reopen if necessary.
