### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by DannyCork** [alexfernandez/loadtest#79]
I am trying to figure out how to send a basic auth header

Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==

So I need to use -H to send a header however -H takes header:value whereas the Auth headers is 
Authoization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxx==== ie, there are spaces in it.

I tried this
    
loadtest -n 10 -c 1 --rps 1 -H Content-Type:application/json Authorization:'Basic YXBpOnB1YmtleS0zMDU2OWE5MGEzNjU2ZjM2OTA4ZWYxYjhkNDJhYzNhNg==' -p dynamic.js http://127.0.0.1:7357
    
but it doesn't work. Any ideas? Thanks.

**Comment by alexfernandez** [comment]
You need to use a `-H` option for each header:

`loadtest … -H Content-Type:application/json -H Authorization:'Basic YXBpOnB1YmtleS0zMDU2OWE5MGEzNjU2ZjM2OTA4ZWYxYjhkNDJhYzNhNg=='

That should do the trick; otherwise please let me know.

**Comment by DannyCork** [comment]
Thanks for the reply. I found that I had to use double quotes around everything after the -H

eg: -H "blah:blah"

loadtest -n 1 -c 1 --rps 1 -H "Content-Type:application/json" -H "Authorization: Basic xxxxxxxxxxxxxxxxxxxx==" -p dynamic.js http://www.www.com

**Comment by alexfernandez** [comment]
Added a note in commit 416fcd1, thanks!
