### ISSUE TITLE
Add cluster support on testserver

### ISSUE THREAD

**Issue by piranna** [alexfernandez/loadtest#80]
This would allow to compare the raw network performance of multicore machines.

**Comment by alexfernandez** [comment]
It's not in the plans, but as always, pull requests are welcome!

**Comment by piranna** [comment]
I'll try to find some time for this. Also an option to use cluster on loadtest would be useful, specially with the concurrent option when testing an external machine, I've found that high `rps` make them get dropped, and I'm not sure if it's the server or the loadtest command getting out of CPU...

**Comment by alexfernandez** [comment]
It's almost definitely the server.

To be sure, what you can do right now is start `n` separate loadtest processes with `--rps` divided between them. For instance, to send 200 rps with 4 cores you can write a Bash script like this:

```
loadtest --rps 50 http://... &
loadtest --rps 50 http://... &
loadtest --rps 50 http://... &
loadtest --rps 50 http://... &
```

It will send the desired rate of 200 rps, although results will be divided in four batches. Doing this with cluster would mean a bit of messaging between workers and master.

For really high request rates I would recommend using `wrk`, but it does not have something similar to `--rps` so it's not a good substitute.

**Comment by piranna** [comment]
> To be sure, what you can do right now is start n separate loadtest processes with --rps divided between them. For instance, to send 200 rps with 4 cores you can write a Bash script like this:
> 
> loadtest --rps 50 http://... &
> loadtest --rps 50 http://... &
> loadtest --rps 50 http://... &
> loadtest --rps 50 http://... &

That's how I was thinking to use cluster here, collecting later the global data ;-)

**Comment by alexfernandez** [comment]
Closing, please reopen if needed.
