### ISSUE TITLE
Using loadtest without http/https (unexpected way)

### ISSUE THREAD

**Issue by FrankHassanabad** [alexfernandez/loadtest#81]
Hi!  Been having a great time using loadtetst.  I used it for `https`, but we have other non-https transport protocols that I wanted to integrate with...So...In a completely unexpected way, I dummy out the request and response node objects with requestGenerator.

I totally don't expect you to support this in any manner, but I wanted to show you how really ...close... your request generator actually is to being transport agnostic which is really cool.

Here is an ES6 pseudo code'ish version:

```javascript
// my values from earlier
const maxRequests       = myMaxRequests;
const concurrency       = myConcurrency;
const requestsPerSecond = myRequestsPerSecond

// load test without using http or https, but rather a different  
// transport protocol.
// I use a dummy return request object as well as a dummy response
// object to accomplish this.
loadTest.loadTest({
  url: 'http://bunk.com',
  maxRequests       : maxRequests,
  concurrency       : concurrency,
  agentKeepAlive    : true,
  requestsPerSecond : requestsPerSecond,
  requestGenerator  : function (params, options, client, callback) {
    return {
      on    : () => {},
      write : () => {},
      end   : () => {
        callback({
          setEncoding : () => {},
          on          : function (signal, onCallback) {
            if (signal === 'end') {
              someNonHttpRequest() // <-- There be the GOLD, my non http promise
              .then((response) => {
                this.statusCode = 200;
                this.body       = response;
                onCallback();
              }).catch((errors) => {
                this.statusCode = errors.statusCode;
                this.body       = errors.body;
                onCallback();
              });
            }
          }
        });
      }
    };
  }
}, (error, result) => {
  //...deal with error and results normally
}
```

**Comment by alexfernandez** [comment]
Actually, loadtest used to support websockets, so it is not as far from testing other protocols. As always, patches are welcome :)

**Comment by iainbryson** [comment]
"used to support websockets" -- you don't any more?  is it a lot of work to add it back?

**Comment by alexfernandez** [comment]
It doesn't support websockets any more. It should not be a lot of effort: add the relevant code, a sample server, and a few tests.

**Comment by iainbryson** [comment]
So, this is something you’d accept a pull request for, if I do the work?

On Sat, Dec 26, 2015 at 2:15 AM, Alex Fernández <notifications@github.com>
wrote:

> It doesn't support websockets any more. It should not be a lot of effort:
> add the relevant code, a sample server, and a few tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexfernandez/loadtest/issues/81#issuecomment-167307559>
> .
>



-- 
— Iain

**Comment by alexfernandez** [comment]
Of course! I already stated so above.

**Comment by iainbryson** [comment]
Nice.  To start, do you have any preferences about websocket libraries?

**Comment by alexfernandez** [comment]
For me, the simpler the better: I used to use [websocket](https://www.npmjs.com/package/websocket), but I don't know if it is up to date.

**Comment by alexfernandez** [comment]
Websockets are working now, thanks to @iainbryson! https://github.com/alexfernandez/loadtest/pull/85
