### ISSUE TITLE
Minor Refactoring

### ISSUE THREAD

**Issue by iainbryson** [alexfernandez/loadtest#88]
It would be good to do the following refactoring:

* Split HttpClient from `loadtest.js` in to its own file
* Make HttpClient inherit from BaseClient so it can share code with the WebSocketClient
* [minor] `getConnect` should have a better name.  It isn't actually creating a connection. It's creating a response handler (as in https://nodejs.org/api/http.html#http_http_request_options_callback ), so maybe createResponseHandler()?
* I can see the logic in keeping unit tests with the code (although it's messy and it might be better to split it out), but having sample.js as a big sample/test in with the lib doesn't make sense to me.  Why not put in in a separate "samples" folder?

If you agree, I can send a pull request. But I didn't want to start on this without getting prior approval.

**Comment by alexfernandez** [comment]
I agree with everything. Moving unit tests to separate files is a worthy endeavor, but I have not had time.

**Comment by alexfernandez** [comment]
Closing, please reopen if needed.
