### ISSUE TITLE
How to make a 'multipart/form-data' in loadtest

### ISSUE THREAD

**Issue by kuldeepJadhav** [alexfernandez/loadtest#89]
'appplication/json' request works for me but now I need to send some json + need to upload 5 files in 1 request

**Comment by alexfernandez** [comment]
Maybe the [`requestGenerator`](https://github.com/alexfernandez/loadtest#-r-requestgeneratormodulejs) is what you need?

**Comment by alexfernandez** [comment]
Closing, please reopen if needed.

**Comment by Erically** [comment]
how to add files in the requestGenerator? any instructions
