### ISSUE TITLE
Support for `PATCH`

### ISSUE THREAD

**Issue by xavierchow** [alexfernandez/loadtest#93]
I have some APIs use `PATCH` method with body, need similar options such as `POST-body` and `POST-file` for patch.

**Comment by alexfernandez** [comment]
Care to send a patch?

**Comment by xavierchow** [comment]
Yes, I'm adhere to [jsonapi spec](http://jsonapi.org/faq/#wheres-put), so instead of `PUT` I'm using `PATCH` for partial updating, it would be really appreciated if loadtest can support `patch-body` or `patch-file` stuff.

**Comment by alexfernandez** [comment]
Sadly I don't have time right now to make the changes myself, but I'm willing to accept a pull request if you can get someone to do the changes.

**Comment by alexfernandez** [comment]
Again, sorry for not noticing #93 for so long. Merged, will appear in version 1.4.0, just published.

**Comment by xavierchow** [comment]
Thanks for merging, closing
