### ISSUE TITLE
Legitimate http codes are considered as errors

### ISSUE THREAD

**Issue by amirsch** [alexfernandez/loadtest#96]
The code treats every http status code above 300 as an error, though for example 302 (redirect) or 304 (not modified)  still indicate success, and the request fails.
I think it might be best to change it to above 400 as these indicate real errors.

**Comment by alexfernandez** [comment]
You are right, changed in commit 6be4495. Published as 1.3.3.

**Comment by kylegoetz** [comment]
Perhaps related to this, but when I run my load test and log the results, the errorCodes property is:

errorCodes: { '-1': 10 }

What is error code -1? I'm unfamiliar with it. But the presence of this in errorCodes suggests why loadtest https://localhost lists nothing but errors and no successes while curl -k https://localhost retrieves the correct data from the server.
