### ISSUE TITLE
"-n and -c" not working as expected

### ISSUE THREAD

**Issue by khangiskhan** [alexfernandez/loadtest#97]
Running "loadtest -n 10 -c 5 -k <url>" returns: 

Max requests:        10
Concurrency level:   5
Agent:               keepalive

Completed requests:  10
Total errors:        0
Total time:          3.1353668470000002 s
Requests per second: 3
Total time:          3.1353668470000002 s

However, in my express server, I am logging requests received, and I am actually receiving 14 TOTAL requests.

I tested the same request using Apache ab, and I receive the correct number of requests.

loadtest version 1.3.3
node version 4.2.2

**Comment by alexfernandez** [comment]
With the current design it is not easy to stop requests at an exact number when there is concurrency, so I chose to just report on the first `n`. I am open to pull requests if you require more precision.

**Comment by alexfernandez** [comment]
I have improved the [documentation](https://github.com/alexfernandez/loadtest#-n-requests) to warn that the number of requests may be > max.

**Comment by khangiskhan** [comment]
How difficult would it be to at least have the results report the number of tests sent? 

Ie if I set "-n 10", have the results report the actual number of requests sent.

**Comment by alexfernandez** [comment]
Not trivial. Right now, each individual client is not aware of the total number of requests, or the share that corresponds to it: when the [total is reached](https://github.com/alexfernandez/loadtest/blob/master/lib/loadtest.js#L432) we simply stop, print the results and kill the clients.

We would need to stop operation and wait for all clients to end, when right now they may not even be waiting for the responses to the last requests.

**Comment by alexfernandez** [comment]
Closing, please reopen if still an issue.
