### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by ozomer** [alexfernandez/loadtest#99]
We are using loadtest in a script on iron.io, where the memory is limited to 320mb.
When we run our script for few minutes, the memory usage increases dramatically until our script crashes. Any suggestions for why this might happen? Does loadtest save all the responses that are returned instead of saving only its statistics?

We are making around ~100 requests per second.

Thanks

**Comment by alexfernandez** [comment]
Hi, I don't have a clue about it. Maybe the garbage collector is not aggressive enough? I will try to reproduce it locally. Can you show me the script so I know what specific features you are using? Thanks!

**Comment by ozomer** [comment]
Probably not a problem with loadtest but a problem with iron.io.
Sometimes the execution on iron.io fails to create connections - in this case the connection requests will be cached, but there will be no responses to clean them. Eventually the process will run out of memory.

Sorry about that, I'm closing this issue.

**Comment by alexfernandez** [comment]
Thanks! Feel free to reopen if it's related to loadtest after all.

**Comment by ozomer** [comment]
The documentation says: "Timeout for each generated request in milliseconds. Default value provided by Node.js client is 3000. Setting this to 0 disables timeout."

But from what I see [here](https://github.com/alexfernandez/loadtest/blob/master/lib/loadtest.js#L209) the timeout timer is created only when the timeout option is set.

Are you sure about the default 3000ms timeout?

**Comment by alexfernandez** [comment]
You are right, I see that [by default there is no timeout](https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback). Changed in the docs and published as 1.3.6. Thanks again!
